name: Notify merged pull request

on:
  pull_request:
    types:
      [ closed ]
jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: send sms to telegram
        id: vars
        run: |
          chatId=-614814904
          botToken=bot5719761998:AAFcnNOlg0P5lU0FvVBd-qVgO-NgzcqXKsk
          telegramUrl="https://api.telegram.org/${botToken}/sendMessage"

          repositoryName=${{github.repository }}

          author=${{github.actor }}

          ref=${{github.ref }}

          pullRequestId=${{github.event.number }}

          pullRequestUrl=${{github.event.pull_request.html_url }}

          curl -d "\
             {
                    \"chat_id\":\"${chatId}\",
                    \"text\":\"Meged pull request: ${pullRequestUrl} \n ${author}\",
                    \"reply_markup\":
                            {
                                    \"inline_keyboard\":
                                            [
                                                    [
                                                            {
                                                                    \"text\": \"${pullRequestId}\",
                                                                    \"url\": \"${pullRequestUrl}\"
                                                            }
                                                    ]
                                            ]
                            }
            }" -H "Content-Type: application/json" -X POST ${telegramUrl}
