name: Notify merged pull request

on:
  push:
    branches:
      - master
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: send sms to telegram
        id: vars
        run: |
          curl -XPOST "https://api.telegram.org/bot5719761998:AAFcnNOlg0P5lU0FvVBd-qVgO-NgzcqXKsk/sendMessage?chat_id=-614814904&text=${{ github.event_name }} commit in ${{ github.repository }} by ${{ github.actor }} ${{github.sha}}@${{ github.ref }} . ${{github.event.pull_request.html_url}}"
#          curl -XPOST "https://api.telegram.org/bot5719761998:AAFcnNOlg0P5lU0FvVBd-qVgO-NgzcqXKsk/sendMessage?chat_id=&text=RELEASED:${{github.event.pull_request.html_url }}user:${{github.event.pull_request.user.login }}"
